version: '3'

services:
    web:
        build:
            context: frontend/
            dockerfile: Dockerfile.dev
        command: ["npm", "run", "start"]
        ports:
            - "3000:3000"

    app:
        build: .
        environment:
            REDIS_URL: redis://redis:6379
            CLICKHOUSE_HOST: $CLICKHOUSE_HOST
            CLICKHOUSE_DATABASE: $CLICKHOUSE_DATABASE
            CLICKHOUSE_USER: $CLICKHOUSE_USER
            CLICKHOUSE_PASSWORD: $CLICKHOUSE_PASSWORD
            CLICKHOUSE_CLUSTER: $CLICKHOUSE_CLUSTER
            CLICKHOUSE_SECURE: $CLICKHOUSE_SECURE
            CLICKHOUSE_VERIFY: $CLICKHOUSE_VERIFY
            CLICKHOUSE_CA: $CLICKHOUSE_CA
        command:
            - bash
            - -c
            - |
                python manage.py migrate
                python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        network_mode: "service:web"

    redis:
        image: redis:6.2.7-alpine
        restart: on-failure
        ports:
            - '6388:6379'
        command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb

    worker:
        build: .
        environment:
            REDIS_URL: redis://redis:6379
            CLICKHOUSE_HOST: $CLICKHOUSE_HOST
            CLICKHOUSE_DATABASE: $CLICKHOUSE_DATABASE
            CLICKHOUSE_USER: $CLICKHOUSE_USER
            CLICKHOUSE_PASSWORD: $CLICKHOUSE_PASSWORD
            CLICKHOUSE_CLUSTER: $CLICKHOUSE_CLUSTER
            CLICKHOUSE_SECURE: $CLICKHOUSE_SECURE
            CLICKHOUSE_VERIFY: $CLICKHOUSE_VERIFY
            CLICKHOUSE_CA: $CLICKHOUSE_CA
        command:
            - ./bin/celery
        volumes:
           - .:/code
