image:
  repository: ghcr.io/posthog/housewatch/api
  frontendRepository: ghcr.io/posthog/housewatch/frontend
  tag: main

nginx:
  image:
    repository: nginx
    tag: stable

clickhouse:
  user: default
  host: clickhouse
  database: default
  secure: "false"
  verify: "false"
  ca: ""

service:
  annotations: {}

web:
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      memory: 500Mi

frontend:
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 2Gi

worker:
  resources:
    requests:
      cpu: 100m
      memory: 1500Mi
    limits:
      memory: 1500Mi

database_url: postgres://housewatch:housewatch@{{ include "postgresql.primary.fullname" .Subcharts.postgresql }}:5432/housewatch
postgresql:
  auth:
    database: housewatch
    username: housewatch
    password: housewatch

rabbitmq:
  auth:
    username: housewatch
    password: housewatch
    erlangCookie: housewatch

redis:
  image:
    repository: redis
    tag: 6.2.7-alpine

  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      memory: 1Gi
